name: CI

on:
  push:
    branches:
      - main
      - release/**

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - release/**
env:
  STEP_TIMEOUT_MINUTES: 60

jobs:
  unit_test:
    name: Unit Tests
    runs-on: ubuntu-latest

    permissions:
      contents: read
      checks: write
      pull-requests: write

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: weather_test_host
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d weather_test_host"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      ConnectionStrings__WeatherDatabase: Host=127.0.0.1;Port=5432;Database=weather_test_host;Username=postgres;Password=postgres;Include Error Detail=true

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        timeout-minutes: ${{ fromJSON(env.STEP_TIMEOUT_MINUTES) }}
        uses: "./.github/steps/install_dependencies"

      - name: Build Inventory.Tests (Release)
        shell: bash
        working-directory: ./Server
        run: dotnet build ./Weather.Tests/Weather.Tests.csproj /p:Configuration=Release /p:OverrideTargetFramework=net10.0 /r

      - name: Run Unit Tests
        shell: bash
        working-directory: ./Server
        run: dotnet test --project ./Weather.Tests/Weather.Tests.csproj --no-build -c Release --results-directory ../TestResults -- --coverage --report-trx

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./TestResults/*.trx

      - name: Publish test results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        with:
          files: ./TestResults/**/*.trx

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ./TestResults/*.coverage
